### ISSUE TITLE
When we tried to run the build for the Android platform on a Windows machine, we encountered the following error.

### ISSUE THREAD

**Issue by Shubham-998877** [numandev1/react-native-keys#80]
Error: Exception in HostObject::get for prop 'Keys': java.lang.UnsatisfiedLinkError: dlopen failed: library "libcrypto.so" not found: needed by /data/app/~~vuvLa52lDkS3-mQAn_dZyA==/**{AppPackageName}**-xRMA9BDKRtV3xToqfFsIXg==/base.apk!/lib/arm64-v8a/libreact-native-keys.so in namespace clns-4

**Comment by malik-javed125** [comment]
got same error, do have any solution for this or still its pending.

**Comment by dule-vikki** [comment]
@numandev1 

Same issue in android devices:
Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/**APP-NAME**--w31qhA-hIbmAW-eDT5ykw==/base.apk"],nativeLibraryDirectories=[/data/app/**APP-NAME**--w31qhA-hIbmAW-eDT5ykw==/lib/x86_64, /system/lib64, /system/vendor/lib64]]] couldn't find "libreact-native-keys.so"

**Version:** 
```
"react-native": "0.76.5",
"react-native-keys": "0.7.10",
```

**Stack trace**
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.finx.vikki--w31qhA-hIbmAW-eDT5ykw==/base.apk"],nativeLibraryDirectories=[/data/app/com.finx.vikki--w31qhA-hIbmAW-eDT5ykw==/lib/x86_64, /system/lib64, /system/vendor/lib64]]] couldn't find "libreact-native-keys.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at com.reactnativekeysjsi.KeysModule.<clinit>(KeysModule.java:48)
       at com.reactnativekeysjsi.KeysModule.getSecureFor(KeysModule.java)
       at APP-NAME.MainApplication.onCreate(MainApplication.kt:56)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
       at android.app.ActivityThread.-wrap1()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:463)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
